### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rename-css-selectors#16]
Seems it fails on javascript files that use object rest/spread.
```
[23:46:18] Error: Line 1: Unexpected token ...
  at ErrorHandler.constructError (/node_modules/recast/node_modules/esprima/dist/esprima.js:5004:22)
  at ErrorHandler.createError (/node_modules/recast/node_modules/esprima/dist/esprima.js:5020:27)
  at JSXParser.Parser.unexpectedTokenError (/node_modules/recast/node_modules/esprima/dist/esprima.js:1985:39)
  at JSXParser.Parser.throwUnexpectedToken (/node_modules/recast/node_modules/esprima/dist/esprima.js:1995:21)
  at JSXParser.Parser.parseObjectPropertyKey (/node_modules/recast/node_modules/esprima/dist/esprima.js:2492:33)
  at JSXParser.Parser.parseObjectProperty (/node_modules/recast/node_modules/esprima/dist/esprima.js:2527:25)
  at JSXParser.Parser.parseObjectInitializer (/node_modules/recast/node_modules/esprima/dist/esprima.js:2595:35)
  at JSXParser.Parser.inheritCoverGrammar (/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
  at JSXParser.Parser.parsePrimaryExpression (/node_modules/recast/node_modules/esprima/dist/esprima.js:2347:38)
  at JSXParser.parsePrimaryExpression (/node_modules/recast/node_modules/esprima/dist/esprima.js:466:97)
```

Espree can be updated to version 4, or to fix that in espree 3, option `experimentalObjectRestSpread: true` can be passed

**Comment by klimashkin** [comment]
In general it would be great to have a way to pass options from `processJs` to espree directly (add some espreeOptions param), because sometimes we want to stop transpiling some ES20XX features without waiting for a whole ES20XX spec to be finalized, as browsers start support it

**Comment by JPeer264** [comment]
@klimashkin thanks for your issue. Oh yes passing the options to espree directly would be great indeed. I will work on that as soon as I have time 👍

**Comment by klimashkin** [comment]
Probably as a fast fix you could release minor update of node-rcs-core that will require espree as `^4.0.0-rc.0 || ^4.0.0`. 
Spec will not be changing and seems like they just wait it to be published to bump final 4.0.0

**Comment by JPeer264** [comment]
The problem is, I just checked, I am not using espree (it was accidentally in the dependencies). I use `recast` which is using `esprima` under the hood. I now have to think about the solution right now, as I can switch the parsers from `recast`. I hope I will find a general solution

**Comment by klimashkin** [comment]
Oh, my bad, I was sure I saw espree in the source.
I think problem with esprima is that it's jquery project that is not really maintained anymore.
espree is better because it uses acorn, which is being developed pretty good.

**Comment by JPeer264** [comment]
Yap, I thought about the same. I think espree is the way to go.

**Comment by JPeer264** [comment]
With `v2.0.0` it should be fixed, and your options are now added. For that, please check out the [parserOptions](https://github.com/JPeer264/node-rename-css-selectors/tree/d0a64f2bc1e19faad6fe49275c2c2308de2661cf#processjs).

**Comment by klimashkin** [comment]
Awesome, it works!
