### ISSUE TITLE
support for pug templates

### ISSUE THREAD

**Issue by grkblood13** [JPeer264/node-rename-css-selectors#22]
Any chance this tool could get builtin support for pug templates?

https://pugjs.org/api/getting-started.html

**Comment by JPeer264** [comment]
Hey, thanks for you issue. This sounds like a great feature. I'll implement this soon :)

**Comment by JPeer264** [comment]
@grkblood13 I am currently implementing this feature. Would you expect the output to be pug or html?

**Comment by grkblood13** [comment]
The output should be pug. The rendering engine will then handle converting that to html for the requester.

**Comment by JPeer264** [comment]
You can now use `rcs.process.pug()`. If you have any issues, please let me know.

**Comment by grkblood13** [comment]
I can't seems to get the pug files to render. It keeps erroring out:

TypeError: Cannot read property 'val' of undefined
    at /home/test/project/node_modules/rename-css-selectors/node_modules/rcs-core/dest/replace/pug.js:82:37
    at Array.map (<anonymous>)
    at /home/test/project/node_modules/rename-css-selectors/node_modules/rcs-core/dest/replace/pug.js:80:43
    at walkAST (/home/test/project/node_modules/pug-walk/index.js:23:18)
    at /home/test/project/node_modules/pug-walk/index.js:104:20
    at Array.reduce (<anonymous>)
    at walkAndMergeNodes (/home/test/project/node_modules/pug-walk/index.js:103:18)
    at walkAST (/home/test/project/node_modules/pug-walk/index.js:37:19)
    at walkAST (/home/test/project/node_modules/pug-walk/index.js:48:21)
    at /home/test/project/node_modules/pug-walk/index.js:104:20

**Comment by JPeer264** [comment]
Can you maybe reduce your pug file to reproduce this and open a new issue?

There might be some `script` or `style` tag in your pug file, which causes this bug.
